-- =============================================================================
-- 内部仓库物品管理 · 数据库结构（表 / 索引 / RLS / 权限）
-- -----------------------------------------------------------------------------
-- 目标库：PostgreSQL 14+（WorkBuddy 云服务、Supabase、自建 PG 均可）
-- 执行顺序：01-schema.sql  →  02-functions.sql  →  03-bootstrap-admin.sql
--                                                      →（可选）04-demo-data.sql
--
-- 这个文件只建"容器"（表、索引、权限），不含任何业务函数；
-- 业务函数在 02-functions.sql。
--
-- 安全模型（很重要，别改）：
--   · 数据是**团队共享**的，不是按人隔离 —— 所以 RLS 策略一律 USING (true)，
--     不要改成按 owner_id / staff_id 隔离，否则员工只能看到自己的私有仓库。
--   · 真正的写入门槛在 02-functions.sql 的 SECURITY DEFINER 函数里（校验登录令牌）。
--   · items 只授予 SELECT（扫码查物品要读），
--     staff / staff_sessions / stock_records **不授予任何表级权限** ——
--     不要"为了方便"给它们补 GRANT，那等于重新打开越权写入的口子。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. 扩展：密码哈希用 crypt() / gen_salt()（bcrypt）
--    若当前库已启用，这句会自动跳过；若报权限不足，说明平台已代为启用，忽略即可。
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- -----------------------------------------------------------------------------
-- 1. auth 辅助函数（RLS 里用来取当前请求的身份）
--    云平台（WorkBuddy 云服务 / Supabase）通常已经提供；
--    如果你的库已存在这三个函数，可整段跳过 —— 下面的写法与平台版本一致。
--    自建 PostgreSQL 时必须有，否则建表语句里的 DEFAULT auth.uid() 会报错。
-- -----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS auth;

CREATE OR REPLACE FUNCTION auth.uid()
RETURNS text
LANGUAGE sql
STABLE
AS $function$
  select
  coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
  )::text
$function$;

CREATE OR REPLACE FUNCTION auth.role()
RETURNS text
LANGUAGE sql
STABLE
AS $function$
  select
  coalesce(
    nullif(current_setting('request.jwt.claim.role', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role')
  )::text
$function$;

CREATE OR REPLACE FUNCTION auth.jwt()
RETURNS jsonb
LANGUAGE sql
STABLE
AS $function$
  select
    nullif(current_setting('request.jwt.claims', true), '')::jsonb
$function$;


-- -----------------------------------------------------------------------------
-- 2. 表结构
-- -----------------------------------------------------------------------------

-- 物品档案。code 是物品编号，同时就是二维码内容（纯 ASCII，扫码枪 / PDA 也能读）
CREATE TABLE IF NOT EXISTS public.items (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code             text        NOT NULL UNIQUE,
  name             text        NOT NULL,
  spec             text,
  category         text,
  unit             text        DEFAULT '个',
  location         text,
  qty              integer     NOT NULL DEFAULT 0,
  min_qty          integer     NOT NULL DEFAULT 0,
  note             text,
  status           text        NOT NULL DEFAULT 'active',
  owner_id         text        DEFAULT auth.uid(),
  owner_name       text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  created_by_id    bigint,
  created_by_name  text,
  updated_by_name  text,
  -- 位置照片：存云端存储的对象路径（shared/<uid>/items/<id>-<ts>.jpg），
  -- 不存 URL、不存 base64 —— 访问时由客户端换签名链接，链接会过期而路径不会。
  photo            text
);
COMMENT ON TABLE public.items IS '仓库物品档案表：code 为物品编号，同时作为二维码内容';

-- 已有库升级用（新建库执行上面那条 CREATE TABLE 时已包含该列，这里是幂等的）
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS photo text;

-- 账号。密码只存 bcrypt 哈希，永不存明文
CREATE TABLE IF NOT EXISTS public.staff (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username             text        NOT NULL UNIQUE,
  password_hash        text        NOT NULL,
  name                 text        NOT NULL,
  phone                text,
  dept                 text,
  role                 text        NOT NULL DEFAULT 'staff'
                                 CHECK (role IN ('admin', 'manager', 'staff')),
  status               text        NOT NULL DEFAULT 'pending'
                                 CHECK (status IN ('pending', 'active', 'rejected', 'disabled')),
  must_change_password boolean     NOT NULL DEFAULT false,
  remark               text,
  review_note          text,
  created_by_id        bigint,
  created_by_name      text,
  reviewed_by_id       bigint,
  reviewed_by_name     text,
  reviewed_at          timestamptz,
  last_login_at        timestamptz,
  login_count          integer     NOT NULL DEFAULT 0,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

-- 登录会话。token 是主键；删除账号时会话级联删除
CREATE TABLE IF NOT EXISTS public.staff_sessions (
  token        text        PRIMARY KEY,
  staff_id     bigint      NOT NULL REFERENCES public.staff(id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL
);

-- 出入库流水。before_qty / after_qty 记下每次操作前后的库存，形成可追溯链条
CREATE TABLE IF NOT EXISTS public.stock_records (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id     bigint      NOT NULL,
  item_code   text        NOT NULL,
  item_name   text        NOT NULL,
  type        text        NOT NULL,
  qty         integer     NOT NULL,
  before_qty  integer,
  after_qty   integer,
  owner_id    text        DEFAULT auth.uid(),
  owner_name  text,
  note        text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  staff_id    bigint,
  staff_role  text,
  staff_name  text
);
COMMENT ON TABLE public.stock_records IS '出入库流水：type 为 in/out，记录操作人与本次数量变化';


-- -----------------------------------------------------------------------------
-- 3. 索引
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS staff_status_idx          ON public.staff (status, role);
CREATE INDEX IF NOT EXISTS staff_sessions_staff_idx  ON public.staff_sessions (staff_id);
CREATE INDEX IF NOT EXISTS stock_records_created_idx ON public.stock_records (created_at DESC);
CREATE INDEX IF NOT EXISTS stock_records_item_idx    ON public.stock_records (item_code);

-- 供 next_item_code() 生成 WP0001 形式的建议编号（独立序列，不隶属于任何表）
CREATE SEQUENCE IF NOT EXISTS public.item_code_seq;


-- -----------------------------------------------------------------------------
-- 4. 行级安全（RLS）
--    items / stock_records 开启；staff / staff_sessions 不开（本来就没有表级授权，
--    外面根本碰不到，函数内部以属主身份访问）
-- -----------------------------------------------------------------------------
ALTER TABLE public.items         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_records ENABLE ROW LEVEL SECURITY;

-- 注意：下面这批策略的 USING / WITH CHECK 全是 true —— 这是刻意的（团队共享）。
-- 策略只决定"哪些行可见"，能不能操作由表级 GRANT 决定。
-- 因此 items 的 INSERT / UPDATE / DELETE 策略虽然存在，
-- 但因为只授了 SELECT，实际是**空转**的（写不进去）。
DROP POLICY IF EXISTS items_read   ON public.items;
DROP POLICY IF EXISTS items_insert ON public.items;
DROP POLICY IF EXISTS items_update ON public.items;
DROP POLICY IF EXISTS items_delete ON public.items;
DROP POLICY IF EXISTS records_read   ON public.stock_records;
DROP POLICY IF EXISTS records_insert ON public.stock_records;

CREATE POLICY items_read   ON public.items         FOR SELECT TO authenticated USING (true);
CREATE POLICY items_insert ON public.items         FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY items_update ON public.items         FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY items_delete ON public.items         FOR DELETE TO authenticated USING (true);

CREATE POLICY records_read   ON public.stock_records FOR SELECT TO authenticated USING (true);
CREATE POLICY records_insert ON public.stock_records FOR INSERT TO authenticated WITH CHECK (true);


-- -----------------------------------------------------------------------------
-- 5. 表 / 序列权限
--    先全部收回，再只放开 items 的只读 —— 这是"不能改"的那一条。
-- -----------------------------------------------------------------------------
REVOKE ALL ON public.items          FROM anon, authenticated;
REVOKE ALL ON public.staff          FROM anon, authenticated;
REVOKE ALL ON public.staff_sessions FROM anon, authenticated;
REVOKE ALL ON public.stock_records  FROM anon, authenticated;

-- 只读：扫码要按编号查物品、列表要分页读物品
GRANT SELECT ON public.items TO anon, authenticated;

-- staff / staff_sessions / stock_records 到此为止：不给任何权限。
-- 它们的读写全部发生在 02-functions.sql 的 SECURITY DEFINER 函数内部。

-- 序列：客户端会直接调用 next_item_code()（它是裸函数、非 SECURITY DEFINER，
-- 以调用者身份执行），所以 anon / authenticated 需要 item_code_seq 的 USAGE。
GRANT USAGE, SELECT ON SEQUENCE public.item_code_seq          TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.items_id_seq           TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.staff_id_seq           TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.stock_records_id_seq   TO anon, authenticated;

-- 可选加固：生产库当前还给序列授了 UPDATE（setval 用得到，但本项目从不调用）。
-- 想更严一点可以补执行：
--   REVOKE UPDATE ON SEQUENCE public.item_code_seq FROM anon, authenticated;
--   REVOKE UPDATE ON SEQUENCE public.items_id_seq, public.staff_id_seq,
--                         public.stock_records_id_seq FROM anon, authenticated;
